### ISSUE TITLE
panic if GetService() is called without a pki document available.

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/client#41]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10871b4]

goroutine 227 [running]:
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session.(*Session).GetService(0x0, 0x12db773, 0x4, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session/session.go:209 +0x34
github.com/katzenpost/kimchi.TestClientConnect.func1(0xc0001bc1e0, 0xc0001ae500, 0xc0001731c0)
	/home/user/go/src/github.com/katzenpost/kimchi/kimchi_test.go:273 +0x373
created by github.com/katzenpost/kimchi.TestClientConnect
	/home/user/go/src/github.com/katzenpost/kimchi/kimchi_test.go:252 +0x130
exit status 2
FAIL	github.com/katzenpost/kimchi	34.709s
```

**Comment by mixmasala** [comment]
no longer applicable
