### ISSUE TITLE
client panics on error from session.sendNext()

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/client#43]
```
panic: minclient: no PKI document for current epoch

goroutine 1142 [running]:
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session.(*Session).lambdaPTask(0xc068ddcb60)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session/worker.go:141 +0x14b
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session.(*Session).worker(0xc068ddcb60)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session/worker.go:110 +0x1b6
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session.(*Session).worker-fm()
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/client/session/session.go:162 +0x2a
github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc068ddcb60, 0xc078fe5bb0)
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:38 +0x4f
created by github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker.(*Worker).Go
	/home/user/go/src/github.com/katzenpost/kimchi/vendor/github.com/katzenpost/core/worker/worker.go:36 +0x9b
exit status 2
FAIL	github.com/katzenpost/kimchi	1408.850s
```
I'm not sure why minclient thinks there is no PKI document for the current epoch (there was a consensus made).
And maybe there should be an error chan rather than panic()?

**Comment by david415** [comment]
isn't this a minclient bug?

**Comment by david415** [comment]
fixed
